package Controller;

import javax.ejb.EJB;
import javax.enterprise.inject.*;

import Application.AuthenticateService;
import br.ufes.inf.nemo.jbutler.ejb.controller.JSFController;

/** TODO: generated by FrameWeb. Should be documented. */
@Model
public class Login Action extends JSFController {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;

	
	/** TODO: generated by FrameWeb. Should be documented. */
	@EJB
	private AuthenticateService authenticateService;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	private String Login;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private String Senha;
	

	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void login() {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void logout() {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void RemindPwd() {
		// FIXME: auto-generated method stub
		return;
	}
	
	
	
	/** Getter for Login. */
	public String getLogin() {
		return Login;
	}

	/** Setter for Login. */
	public void setLogin(String Login) {
		this.Login = Login;
	}
	
	/** Getter for Senha. */
	public String getSenha() {
		return Senha;
	}

	/** Setter for Senha. */
	public void setSenha(String Senha) {
		this.Senha = Senha;
	}
	
}