# Generated by Django 3.1.7 on 2021-04-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='interesse',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
