# Generated by Django 3.2 on 2021-04-15 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0006_auto_20210414_2148'),
        ('costumer', '0002_alter_ordem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='accepted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='livre',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='ordem',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professional.profissional'),
        ),
    ]
