# Generated by Django 3.2 on 2021-04-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0003_auto_20210414_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='livre',
            field=models.BooleanField(default=True),
        ),
    ]
