# Generated by Django 3.2 on 2021-04-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumer', '0004_auto_20210416_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='status',
            field=models.CharField(choices=[('STAND BY', 'STAND BY'), ('EM OPERAÇÃO', 'EM OPERAÇÃO'), ('FINALIZADO', 'FINALIZADO')], default='STAND BY', max_length=120, null=True),
        ),
    ]
