# Generated by Django 3.1.7 on 2021-04-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0002_professional_rating'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.person')),
                ('interested_in', models.CharField(max_length=128, null=True)),
            ],
            bases=('register.person',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('STAND BY', 'STAND BY'), ('EM OPERAÇÃO', 'EM OPERAÇÃO'), ('FINALIZADO', 'FINALIZADO')], max_length=120, null=True)),
                ('free', models.BooleanField(default=True, null=True)),
                ('accepted', models.BooleanField(default=False, null=True)),
                ('competence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professional.competence')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='professional.professional')),
            ],
        ),
    ]
