# Generated by Django 3.1.7 on 2021-04-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.pessoa')),
                ('cpf', models.CharField(max_length=14, null=True)),
                ('contato', models.CharField(max_length=20, null=True)),
                ('media', models.FloatField(null=True)),
            ],
            bases=('register.pessoa',),
        ),
    ]
