# Generated by Django 3.2 on 2021-04-16 16:05

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.person')),
                ('cpf', cpf_field.models.CPFField(max_length=14, null=True, verbose_name='cpf')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BR')),
                ('average', models.FloatField(null=True)),
                ('competence', models.ManyToManyField(to='professional.Competence')),
            ],
            bases=('register.person',),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='professional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.professional'),
        ),
    ]
