# Generated by Django 3.1.7 on 2021-04-03 13:25

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, null=True, verbose_name='cpf'),
        ),
    ]
