# Generated by Django 3.1.7 on 2021-04-16 16:30

import cpf_field.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='register.person')),
                ('cpf', cpf_field.models.CPFField(max_length=14, null=True, verbose_name='cpf')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BR')),
                ('average', models.FloatField(null=True)),
                ('competence', models.ManyToManyField(to='professional.Competence')),
            ],
            bases=('register.person',),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=120, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.professional')),
            ],
        ),
    ]
