# Generated by Django 3.1.7 on 2021-04-03 14:25

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_auto_20210403_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='contato',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='BR'),
        ),
    ]
