# Generated by Django 3.2 on 2021-04-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0002_profissional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='contato',
            new_name='telefone',
        ),
    ]
