# Generated by Django 3.2 on 2021-04-09 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0003_rename_contato_profissional_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('descricao', models.CharField(max_length=120, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profissional',
            name='competencia',
            field=models.ManyToManyField(null=True, to='professional.Competencia'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='avaliacao',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='professional.avaliacao'),
        ),
    ]
