# Generated by Django 3.2 on 2021-04-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0004_auto_20210409_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='competencia',
            field=models.ManyToManyField(to='professional.Competencia'),
        ),
    ]
