# Generated by Django 3.2 on 2021-04-16 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0006_auto_20210414_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profissional',
            old_name='competencia',
            new_name='competencias',
        ),
    ]
