# Generated by Django 3.2.3 on 2021-05-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professional', '0008_competencia_creator_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='descricao',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
