package Application.Package Package;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface AuthenticateService extends Serializable {
	
}