package Application Package;

import javax.ejb.EJB;
import javax.ejb.Stateless;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class Avaliação implements Avaliação {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private int nota;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private String descrição;
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private Date data;
	

		
	/** Getter for nota. */
	public int getNota() {
		return nota;
	}
	
	/** Setter for nota. */
	public void setNota(int nota) {
		this.nota = nota;
	}
		
	/** Getter for descrição. */
	public String getDescrição() {
		return descrição;
	}
	
	/** Setter for descrição. */
	public void setDescrição(String descrição) {
		this.descrição = descrição;
	}
		
	/** Getter for data. */
	public Date getData() {
		return data;
	}
	
	/** Setter for data. */
	public void setData(Date data) {
		this.data = data;
	}
	
	
	
}