package Application Package;

import javax.ejb.EJB;
import javax.ejb.Stateless;

/** TODO: generated by FrameWeb. Should be documented. */
@Stateless
public class Profissional implements Profissional {
	/** Serialization id (using default value, change if necessary). */
	private static final long serialVersionUID = 1L;
	
	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	private int cpf;
	

		
	/** Getter for cpf. */
	public int getCpf() {
		return cpf;
	}
	
	/** Setter for cpf. */
	public void setCpf(int cpf) {
		this.cpf = cpf;
	}
	
	
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void ValidarCPF() {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void SelectID() {
		// FIXME: auto-generated method stub
		return;
	}
	
	/** TODO: generated by FrameWeb. Should be documented. */
	@Override
	public void list() {
		// FIXME: auto-generated method stub
		return;
	}
	
}