package Application Package;

import java.io.Serializable;
import javax.ejb.Local;

/** TODO: generated by FrameWeb. Should be documented. */
@Local
public interface ProfissionalManageServices extends Serializable {
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void ValidarCPF();
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void SelectID();
	
	/** TODO: generated by FrameWeb. Should be documented. */
	public void list();
	
}