package Entity Package;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Avaliação extends PersistentObjectSupport implements Comparable<Avaliação> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private int nota;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String descrição;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private Date data;







	/** Getter for nota. */
	public int getNota() {
		return nota;
	}
	
	/** Setter for nota. */
	public void setNota(int nota) {
		this.nota = nota;
	}

	/** Getter for descrição. */
	public String getDescrição() {
		return descrição;
	}
	
	/** Setter for descrição. */
	public void setDescrição(String descrição) {
		this.descrição = descrição;
	}

	/** Getter for data. */
	public Date getData() {
		return data;
	}
	
	/** Setter for data. */
	public void setData(Date data) {
		this.data = data;
	}







	/** TODO: generated by FrameWeb. Should be documented. */
	
	public void New Method() {
		// FIXME: auto-generated method stub
		return;
	}
	


	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Avaliação o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}