package Entity Package;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Cliente extends PersistentObjectSupport implements Comparable<Cliente> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String interesse;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne
		private Pessoa Target;
		
	




	/** Getter for interesse. */
	public String getInteresse() {
		return interesse;
	}
	
	/** Setter for interesse. */
	public void setInteresse(String interesse) {
		this.interesse = interesse;
	}




		
		/** Getter for Target. */
		public Pessoa getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Pessoa Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Cliente o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}