package Entity Package;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Competencia extends PersistentObjectSupport implements Comparable<Competencia> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String descrição;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne
		private Competencia Source;
		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne(mappedBy="Source")
		private Competencia Target;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for descrição. */
	public String getDescrição() {
		return descrição;
	}
	
	/** Setter for descrição. */
	public void setDescrição(String descrição) {
		this.descrição = descrição;
	}




		
		/** Getter for Source. */
		public Competencia getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Competencia Source) {
			this.Source = Source;
		}
		
		/** Getter for Target. */
		public Competencia getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Competencia Target) {
			this.Target = Target;
		}
		
	





	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Competencia o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}