package Entity Package;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Ocupação extends PersistentObjectSupport implements Comparable<Ocupação> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	public  New Attribute;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private int tipo;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String descrição;







	/** Getter for New Attribute. */
	public  getNew Attribute() {
		return New Attribute;
	}
	
	/** Setter for New Attribute. */
	public void setNew Attribute( New Attribute) {
		this.New Attribute = New Attribute;
	}

	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for tipo. */
	public int getTipo() {
		return tipo;
	}
	
	/** Setter for tipo. */
	public void setTipo(int tipo) {
		this.tipo = tipo;
	}

	/** Getter for descrição. */
	public String getDescrição() {
		return descrição;
	}
	
	/** Setter for descrição. */
	public void setDescrição(String descrição) {
		this.descrição = descrição;
	}








	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Ocupação o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}