package Entity Package;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Pessoa extends PersistentObjectSupport implements Comparable<Pessoa> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String nome;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private char sexo;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String email;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private Date nascimento;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private password senha;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne(mappedBy="Target")
		private Cliente Source;
		
	

		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne(mappedBy="Target")
		private Profissional Source;
		
	




	/** Getter for nome. */
	public String getNome() {
		return nome;
	}
	
	/** Setter for nome. */
	public void setNome(String nome) {
		this.nome = nome;
	}

	/** Getter for sexo. */
	public char getSexo() {
		return sexo;
	}
	
	/** Setter for sexo. */
	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

	/** Getter for email. */
	public String getEmail() {
		return email;
	}
	
	/** Setter for email. */
	public void setEmail(String email) {
		this.email = email;
	}

	/** Getter for nascimento. */
	public Date getNascimento() {
		return nascimento;
	}
	
	/** Setter for nascimento. */
	public void setNascimento(Date nascimento) {
		this.nascimento = nascimento;
	}

	/** Getter for senha. */
	public password getSenha() {
		return senha;
	}
	
	/** Setter for senha. */
	public void setSenha(password senha) {
		this.senha = senha;
	}




		
		/** Getter for Source. */
		public Cliente getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Cliente Source) {
			this.Source = Source;
		}
		
	

		
		/** Getter for Source. */
		public Profissional getSource() {
			return Source;
		}
		
		/** Setter for Source. */
		public void setSource(Profissional Source) {
			this.Source = Source;
		}
		
	




	/** TODO: generated by FrameWeb. Should be documented. */
	
	public void ValidarEmail() {
		// FIXME: auto-generated method stub
		return;
	}
	

	/** TODO: generated by FrameWeb. Should be documented. */
	
	public void ValidarSenha() {
		// FIXME: auto-generated method stub
		return;
	}
	


	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Pessoa o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}