package Entity Package;

import java.util.*;
import java.math.*;
import javax.persistence.*;
import javax.validation.constraints.*;
import br.ufes.inf.nemo.jbutler.ejb.persistence.PersistentObjectSupport;

/** TODO: generated by FrameWeb. Should be documented. */
@Entity
public class Profissional extends PersistentObjectSupport implements Comparable<Profissional> {
	/** Serialization id. */
	private static final long serialVersionUID = 1L;



	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private int cpf;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String contato;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private Float media;

	/** TODO: generated by FrameWeb. Should be documented. false */
	@NotNull  
	private String cidade;




		
		/** TODO: generated by FrameWeb. Should be documented. */
		@OneToOne
		private Pessoa Target;
		
	




	/** Getter for cpf. */
	public int getCpf() {
		return cpf;
	}
	
	/** Setter for cpf. */
	public void setCpf(int cpf) {
		this.cpf = cpf;
	}

	/** Getter for contato. */
	public String getContato() {
		return contato;
	}
	
	/** Setter for contato. */
	public void setContato(String contato) {
		this.contato = contato;
	}

	/** Getter for media. */
	public Float getMedia() {
		return media;
	}
	
	/** Setter for media. */
	public void setMedia(Float media) {
		this.media = media;
	}

	/** Getter for cidade. */
	public String getCidade() {
		return cidade;
	}
	
	/** Setter for cidade. */
	public void setCidade(String cidade) {
		this.cidade = cidade;
	}




		
		/** Getter for Target. */
		public Pessoa getTarget() {
			return Target;
		}
		
		/** Setter for Target. */
		public void setTarget(Pessoa Target) {
			this.Target = Target;
		}
		
	




	/** TODO: generated by FrameWeb. Should be documented. */
	
	public void ValidarEmail() {
		// FIXME: auto-generated method stub
		return;
	}
	

	/** TODO: generated by FrameWeb. Should be documented. */
	
	public void ValidarSenha() {
		// FIXME: auto-generated method stub
		return;
	}
	


	/** @see java.lang.Comparable#compareTo(java.lang.Object) */
	@Override
	public int compareTo(Profissional o) {
		// FIXME: auto-generated method stub		
		return super.compareTo(o);
	}
}