# Generated by Django 3.1.7 on 2021-04-03 09:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True)),
                ('categoria', models.CharField(choices=[('CATEGORIA 1', 'CATEGORIA 1'), ('CATEGORIA 2', 'CATEGORIA 2'), ('CATEGORIA 3', 'CATEGORIA 3')], max_length=120, null=True)),
                ('descricao', models.CharField(max_length=120, null=True)),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nome', models.CharField(max_length=120, null=True)),
                ('sexo', models.CharField(max_length=1, null=True)),
                ('cidade', models.CharField(max_length=120, null=True)),
                ('nascimento', models.DateField(default=datetime.date.today, null=True)),
                ('user_type', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('STAND BY', 'STAND BY'), ('EM OPERATAÇÃO', 'EM OPERAÇÂO'), ('FINALIZADO', 'FINALIZADO')], max_length=120, null=True)),
                ('competencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.competencia')),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='register.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='competencia',
            name='tags',
            field=models.ManyToManyField(to='register.Tag'),
        ),
    ]
