# Generated by Django 3.1.6 on 2021-02-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
