# Generated by Django 3.1.6 on 2021-02-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_pessoa_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('perfil', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(max_length=120)),
            ],
        ),
    ]
