# Generated by Django 3.1.6 on 2021-02-17 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_vagas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vagas',
            new_name='Vaga',
        ),
    ]
