# Generated by Django 3.2 on 2021-04-07 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210403_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competencia',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
