# Generated by Django 3.1.7 on 2021-03-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20210331_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='CEP',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
