# Generated by Django 3.1.7 on 2021-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20210331_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True)),
                ('categoria', models.CharField(choices=[('CATEGORIA 1', 'CATEGORIA 1'), ('CATEGORIA 2', 'CATEGORIA 2'), ('CATEGORIA 3', 'CATEGORIA 3')], max_length=120, null=True)),
                ('descricao', models.CharField(max_length=120, null=True)),
                ('data_created', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_created', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
