# Generated by Django 3.1.7 on 2021-03-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20210331_1339'),
        ('register', '0004_remove_pessoa_username'),
    ]

    operations = [
    ]
