# Generated by Django 3.1.7 on 2021-03-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_competencia_ordem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordem',
            name='status',
            field=models.CharField(choices=[('STANDBY', 'STANDBY'), ('EM OPERATAÇÃO', 'EM OPERAÇÂO'), ('FINALIZADO', 'FINALIZADO')], max_length=120, null=True),
        ),
    ]
