# Generated by Django 3.1.7 on 2021-03-31 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_merge_20210331_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='USERNAME_FIELD',
            field=models.CharField(default='username', max_length=150),
        ),
    ]
