# Generated by Django 3.1.7 on 2021-03-31 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_pessoa_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='USERNAME_FIELD',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
