# Generated by Django 3.1.7 on 2021-03-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20210331_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ordem',
            name='tags',
            field=models.ManyToManyField(to='register.Tag'),
        ),
    ]
