# Generated by Django 3.1.7 on 2021-03-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20210331_1957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem',
            name='tags',
        ),
        migrations.AddField(
            model_name='competencia',
            name='tags',
            field=models.ManyToManyField(to='register.Tag'),
        ),
    ]
