# Generated by Django 3.1.7 on 2021-04-01 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20210401_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='status',
            field=models.CharField(choices=[('STAND BY', 'STAND BY'), ('EM OPERATAÇÃO', 'EM OPERAÇÂO'), ('FINALIZADO', 'FINALIZADO')], max_length=120, null=True),
        ),
    ]
